spring:
  application:
    name: gscore

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000  # 30 seconds to handle cold starts
      idle-timeout: 600000  # 10 minutes
      max-lifetime: 1800000  # 30 minutes

  jpa:
    hibernate:
      ddl-auto: none   #using Flyway to manage
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml