CREATE TABLE scores
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sbd          VARCHAR(20)                             NOT NULL,
    subject_code VARCHAR                                 NOT NULL,
    score        DOUBLE PRECISION,
    CONSTRAINT pk_scores PRIMARY KEY (id)
);

CREATE TABLE students
(
    sbd          VARCHAR(20) NOT NULL,
    ma_ngoai_ngu VARCHAR(10),
    CONSTRAINT pk_students PRIMARY KEY (sbd)
);

CREATE TABLE subjects
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(50)                             NOT NULL,
    name VARCHAR(100),
    CONSTRAINT pk_subjects PRIMARY KEY (id)
);

ALTER TABLE subjects
    ADD CONSTRAINT uc_subjects_code UNIQUE (code);

ALTER TABLE scores
    ADD CONSTRAINT FK_SCORES_ON_SBD FOREIGN KEY (sbd) REFERENCES students (sbd);

ALTER TABLE scores
    ADD CONSTRAINT FK_SCORES_ON_SUBJECT_CODE FOREIGN KEY (subject_code) REFERENCES subjects (code);